#---------------------------------------------------------------------------------
#               Document Generator Project
#			        by Peter Antoine
#
#   @file: makefile
#   @desc: This file will build the document linker executable.
#
# @author: 
#   @date: 05/07/2012 19:02:16
#---------------------------------------------------------------------------------
#                     Copyright (c) 2012 Peter Antoine
#                            All rights Reserved.
#                    Released Under the Artistic Licence
#---------------------------------------------------------------------------------

DEPENDENCES = common
INCLUDE_DIRS += -I $(BUILD_ROOT)/common/include

#---------------------------------------------------------------------------------
# The build includes
#---------------------------------------------------------------------------------
include $(BUILD_ROOT)/build/make_executable.mak
include $(BUILD_ROOT)/build/make_docs.mak

